name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:13.6.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        run: npx cypress run --browser chrome --config video=true,screenshotOnRunFailure=true,viewportWidth=1280,viewportHeight=720 --reporter mochawesome
        env:
          CYPRESS_RETRIES: 2
          DEBUG: cypress:*
          CI: true

      - name: Generate HTML report
        run: npx mochawesome-merge cypress/results/*.json > cypress/results/report.json && npx mochawesome-report-generator cypress/results/report.json --reportDir cypress/results/html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/results/
            cypress/videos/
            cypress/screenshots/
            mochawesome-report/
          retention-days: 5 