name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:13.6.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        run: npm run generate-all-reports
        env:
          CYPRESS_RETRIES: 2
          CI: true
          CYPRESS_VIDEO: true
          CYPRESS_VIDEO_COMPRESSION: 32

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            results/
            cypress/videos/
            cypress/screenshots/
            mochawesome-report/
          retention-days: 5 